name: Test Online Banking app

on: [push]

jobs:
  Testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '20.x'
    - name: Install dependencies
      run: |
        cd LR3-4/
        cd banking/
        npm install
    - name: Run tests
      env:
        DB_URL: ${{ secrets.DB_URL }}
        DB_KEY: ${{ secrets.DB_KEY }}
        DB_KEY_ADMIN: ${{ secrets.DB_KEY_ADMIN }}
      run: |
        cd LR3-4/
        cd banking/
        npm run test:ci