name: Test Online Banking app

on: [push]

jobs:
  runtest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '20.x'
    - name: Install dependencies
      run: |
        cd LR3-4/
        cd banking/
        npm install
    - name: Run tests
      run: |
        cd LR3-4/
        cd banking/
        npm run test:ci